version: '3.8'

services:

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 10a0795ba77b58ef34755956aa379fb33bb441f2e6db36f2e63c637c7c3c6dec
    ports:
      - "5432:5432"